export const GET_CARD = 'GET_CARD';
export const GET_CARD_SUCCESS = 'GET_CARD_SUCCESS';
export const GET_CARD_FAIL = 'GET_CARD_FAIL';
export const HUMAN_CLAIM_SIGNATURE = 'HUMAN_CLAIM_SIGNATURE';
export const HUMAN_CLAIM_SIGNATURE_SUCCESS = 'HUMAN_CLAIM_SIGNATURE_SUCCESS';
export const HUMAN_CLAIM_SIGNATURE_FAIL = 'HUMAN_CLAIM_SIGNATURE_FAIL';
export const CLEAR_CARD = 'CLEAR_CARD';

export const SUPPORT_HUMAN_CLAIM_SIGNATURE = 'SUPPORT_HUMAN_CLAIM_SIGNATURE';
export const SUPPORT_HUMAN_CLAIM_SIGNATURE_SUCCESS = 'SUPPORT_HUMAN_CLAIM_SIGNATURE_SUCCESS';
export const SUPPORT_HUMAN_CLAIM_SIGNATURE_FAIL = 'SUPPORT_HUMAN_CLAIM_SIGNATURE_FAIL';
export const REVOKE_SUPPORT_HUMAN_CLAIM_SIGNATURE = 'REVOKE_SUPPORT_HUMAN_CLAIM_SIGNATURE';
export const REVOKE_SUPPORT_HUMAN_CLAIM_SIGNATURE_SUCCESS = 'REVOKE_SUPPORT_HUMAN_CLAIM_SIGNATURE_SUCCESS';
export const REVOKE_SUPPORT_HUMAN_CLAIM_SIGNATURE_FAIL = 'REVOKE_SUPPORT_HUMAN_CLAIM_SIGNATURE_FAIL';

export const ADD_LINK_DIGITAL_PROPERTY = 'ADD_LINK_DIGITAL_PROPERTY';
export const ADD_LINK_DIGITAL_PROPERTY_SUCCESS = 'ADD_LINK_DIGITAL_PROPERTY_SUCCESS';
export const ADD_LINK_DIGITAL_PROPERTY_FAIL = 'ADD_LINK_DIGITAL_PROPERTY_FAIL';
export const REVOKE_LINK_DIGITAL_PROPERTY = 'REVOKE_LINK_DIGITAL_PROPERTY';
export const REVOKE_LINK_DIGITAL_PROPERTY_SUCCESS = 'REVOKE_LINK_DIGITAL_PROPERTY_SUCCESS';
export const REVOKE_LINK_DIGITAL_PROPERTY_FAIL = 'REVOKE_LINK_DIGITAL_PROPERTY_FAIL';
export const PROOF_LINK_DIGITAL_PROPERTY = 'PROOF_LINK_DIGITAL_PROPERTY';
export const PROOF_LINK_DIGITAL_PROPERTY_SUCCESS = 'PROOF_LINK_DIGITAL_PROPERTY_SUCCESS';
export const PROOF_LINK_DIGITAL_PROPERTY_FAIL = 'PROOF_LINK_DIGITAL_PROPERTY_FAIL';
