export const LOAD_BOOKTREE = 'LOAD_BOOKTREE';
export const LOAD_BOOKTREE_SUCCESS = 'LOAD_BOOKTREE_SUCCESS';
export const LOAD_BOOKTREE_FAIL = 'LOAD_BOOKTREE_FAIL';

export const SHOW_BOOK = 'SHOW_BOOK';
export const SHOW_BOOK_SUCCESS = 'SHOW_BOOK_SUCCESS';
export const SHOW_BOOK_FAIL = 'SHOW_BOOK_FAIL';

export const SHOW_NEXT_BOOK = 'SHOW_NEXT_BOOK';
export const SHOW_NEXT_BOOK_SUCCESS = 'SHOW_NEXT_BOOK_SUCCESS';
export const SHOW_NEXT_BOOK_FAIL = 'SHOW_NEXT_BOOK_FAIL';

export const CREATE_BOOK = 'CREATE_BOOK';
export const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS';
export const CREATE_BOOK_FAIL = 'CREATE_BOOK_FAIL';

export const EDIT_BOOK = 'EDIT_BOOK';
export const EDIT_BOOK_SUCCESS = 'EDIT_BOOK_SUCCESS';
export const EDIT_BOOK_FAIL = 'EDIT_BOOK_FAIL';

export const MOVE_BOOK = 'MOVE_BOOK';
export const MOVE_BOOK_SUCCESS = 'MOVE_BOOK_SUCCESS';
export const MOVE_BOOK_FAIL = 'MOVE_BOOK_FAIL';

export const GET_ARR_CHECKBOX = 'GET_ARR_CHECKBOX';

export const UPLOAD_BOOK_COVER = 'UPLOAD_BOOK_COVER';
export const UPLOAD_BOOK_COVER_SUCCESS = 'UPLOAD_BOOK_COVER_SUCCESS';
export const UPLOAD_BOOK_COVER_FAIL = 'UPLOAD_BOOK_COVER_FAIL';

export const CLEAR_BOOKSTORIES = 'CLEAR_BOOKSTORIES';
export const CLEAR_BOOKTREE = 'CLEAR_BOOKTREE';
export const UPLOAD_BOOK_COVER_BASE64 = 'UPLOAD_BOOK_COVER_BASE64';

export const SHOW_SUBBOKS_CURRENT_BOOK = 'SHOW_SUBBOKS_CURRENT_BOOK';

export const GET_BOOKS = 'GET_BOOKS';
export const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS';
export const GET_BOOKS_FAIL = 'GET_BOOKS_FAIL';

export const DELETE_BOOK = 'DELETE_BOOK';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
export const DELETE_BOOK_FAIL = 'DELETE_BOOK_FAIL';
