export const GET_ALL_PHOTOS = 'GET_ALL_PHOTOS';
export const GET_ALL_PHOTOS_SUCCESS = 'GET_ALL_PHOTOS_SUCCESS';
export const GET_ALL_PHOTOS_FAIL = 'GET_ALL_PHOTOS_FAIL';

export const GET_PROFILE_PHOTOS = 'GET_PROFILE_PHOTOS';
export const GET_PROFILE_PHOTOS_SUCCESS = 'GET_PROFILE_PHOTOS_SUCCESS';
export const GET_PROFILE_PHOTOS_FAIL = 'GET_PROFILE_PHOTOS_FAIL';

export const GET_COVERS_PHOTOS = 'GET_COVERS_PHOTOS';
export const GET_COVERS_PHOTOS_SUCCESS = 'GET_COVERS_PHOTOS_SUCCESS';
export const GET_COVERS_PHOTOS_FAIL = 'GET_COVERS_PHOTOS_FAIL';
