export const GET_DATA_TEMPLATES = 'GET_DATA_TEMPLATES';
export const GET_DATA_TEMPLATES_SUCCESS = 'GET_DATA_TEMPLATES_SUCCESS';
export const GET_DATA_TEMPLATES_FAIL = 'GET_DATA_TEMPLATES_FAIL';

export const GET_HTML_TEMPLATE_BY_LINK = 'GET_HTML_TEMPLATE_BY_LINK';
export const GET_HTML_TEMPLATE_BY_LINK_SUCCESS = 'GET_HTML_TEMPLATE_BY_LINK_SUCCESS';
export const GET_HTML_TEMPLATE_BY_LINK_FAIL = 'GET_HTML_TEMPLATE_BY_LINK_FAIL';
