export const LOAD_SHOW_USER_STORIES = 'LOAD_SHOW_USER_STORIES';
export const LOAD_SHOW_USER_STORIES_SUCCESS = 'LOAD_SHOW_USER_STORIES_SUCCESS';
export const LOAD_SHOW_USER_STORIES_FAIL = 'LOAD_SHOW_USER_STORIES_FAIL';

export const LOAD_NEXT_SHOW_USER_STORIES = 'LOAD_NEXT_SHOW_USER_STORIES';
export const LOAD_NEXT_SHOW_USER_STORIES_SUCCESS = 'LOAD_NEXT_SHOW_USER_STORIES_SUCCESS';
export const LOAD_NEXT_SHOW_USER_STORIES_FAIL = 'LOAD_NEXT_SHOW_USER_STORIES_FAIL';

export const CREATE_STORY = 'CREATE_STORY';
export const CREATE_STORY_SUCCESS = 'CREATE_STORY_SUCCESS';
export const CREATE_STORY_FAIL = 'CREATE_STORY_FAIL';

export const CLEAR_PAGINATION = 'CLEAR_PAGINATION';

export const LIKE_STORY = 'LIKE_STORY';
export const LIKE_STORY_SUCCESS = 'LIKE_STORY_SUCCESS';
export const LIKE_STORY_FAIL = 'LIKE_STORY_FAIL';

export const RELOG_STORY = 'RELOG_STORY';
export const RELOG_STORY_SUCCESS = 'RELOG_STORY_SUCCESS';
export const RELOG_STORY_FAIL = 'RELOG_STORY_FAIL';

export const SET_VISIBILITY_STORY = 'SET_VISIBILITY_STORY';
export const SET_VISIBILITY_STORY_SUCCESS = 'SET_VISIBILITY_STORY_SUCCESS';
export const SET_VISIBILITY_STORY_FAIL = 'SET_VISIBILITY_STORY_FAIL';

export const GET_STORY = 'GET_STORY';
export const GET_STORY_SUCCESS = 'GET_STORY_SUCCESS';
export const GET_STORY_FAIL = 'GET_STORY_FAIL';

export const DELETE_STORY = 'DELETE_STORY';
export const DELETE_STORY_SUCCESS = 'DELETE_STORY_SUCCESS';
export const DELETE_STORY_FAIL = 'DELETE_STORY_FAIL';

export const PIN_STORY = 'PIN_STORY';
export const PIN_STORY_SUCCESS = 'PIN_STORY_SUCCESS';
export const PIN_STORY_FAIL = 'PIN_STORY_FAIL';

export const CREATE_NEW_COMMENT = 'CREATE_NEW_COMMENT';
export const CREATE_NEW_COMMENT_SUCCESS = 'CREATE_NEW_COMMENT_SUCCESS';
export const CREATE_NEW_COMMENT_FAIL = 'CREATE_NEW_COMMENT_FAIL';

export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS';
export const UPDATE_COMMENT_FAIL = 'UPDATE_COMMENT_FAIL';

export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';

export const VIEW_MORE_COMMENTS = 'VIEW_MORE_COMMENTS';
export const VIEW_MORE_COMMENTS_SUCCESS = 'VIEW_MORE_COMMENTS_SUCCESS';
export const VIEW_MORE_COMMENTS_FAIL = 'VIEW_MORE_COMMENTS_FAIL';

export const CLEAR_STORIES = 'CLEAR_STORIES';

export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_FAIL = 'UPLOAD_FILE_FAIL';

export const SHOW_COMMENT = 'SHOW_COMMENT';
export const SHOW_COMMENT_SUCCESS = 'SHOW_COMMENT_SUCCESS';
export const SHOW_COMMENT_FAIL = 'SHOW_COMMENT_FAIL';
