import React, { Component } from 'react';
import { Modal } from 'react-bootstrap';
import './tweet-modal.scss'; 

class TweetModal extends Component {

  onSaveChangesClick = () => {
    this.props.checkTweetHandler();
  }

  openTwitter = () => {
    const { card, user_slug } = this.props;

    window.open(`https://twitter.com/intent/tweet?source=webclient&text=Proving+ownership+over+my+Twitter+account.+Posting+random+number+generated+by+Validbook:+${card.random_number}+/+http://futurama11001111.validbook.org/${user_slug}/documents/account-card/${card.public_address}/${card.random_number}`);
  }

  render() {
    const { showModal, closeModalHandler, checkTweetHandler, card, user_slug } = this.props;

    return (
      <Modal
        show={showModal}
        onHide={closeModalHandler || checkTweetHandler}
      >
        <Modal.Header closeButton>
          <Modal.Title>Prove your Twitter identity</Modal.Title>
        </Modal.Header>

        <Modal.Body>
          <div className="tweet-modal-body">
            <div className="open-tweet-in-new-tab">
              Please tweet the below text, exactly as it appears.
              (<span className="open-in-new-tab-icon"/><a href="#" onClick={this.openTwitter}>twitter popup</a>)
            </div>
            <textarea value={`Proving ownership over my Twitter account. Posting random number generated by Validbook: ${card.random_number} / http://futurama11001111.validbook.org/${user_slug}/documents/account-card/${card.public_address}/${card.random_number}`}/>
          </div>
        </Modal.Body>

        <Modal.Footer>
          <button 
            className="btn-brand btn-cancel" 
            onClick={closeModalHandler}>Cancel</button>
          <button 
            className="btn-brand" 
            style={{marginLeft: '16px'}} 
            onClick={this.onSaveChangesClick}>Ok, I tweeted! Check for it</button>
        </Modal.Footer>
      </Modal>
    );
  }
}

export default TweetModal;
